# Generated by Django 4.2.7 on 2023-11-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentalstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentalstate',
            old_name='cause',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='mentalstate',
            name='mood',
        ),
    ]
